[phases.build]
cmds = [
  "cd fast-api-backend && pip install -r requirements.txt && echo 'Backend dependencies installed'",
  "cd random_name_frontend && npm install && echo 'Frontend dependencies installed'",
  "cd random_name_frontend && npm run build && echo 'Frontend built'"
]

[start]
cmd = "cd fast-api-backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} & cd random_name_frontend && npm start"
