[build]
  # Usar pip para instalar dependencias de Python
  command = "cd fast-api-backend && pip install -r requirements.txt"

[deploy]
  # Usar npm para construir el frontend
  command = "cd random_name_frontend && npm install && npm run build"

[start]
  # Comando para iniciar el backend y frontend (ajusta según tus necesidades)
  command = "cd fast-api-backend && uvicorn main:app --host 0.0.0.0 --port 8000 & cd ../random_name_frontend && npm start"
