[phases.build]
  commands = [
    "cd fast-api-backend && pip install -r requirements.txt",
    "cd random_name_frontend && npm install && npm run build"
  ]

[phases.start]
  commands = [
    "cd fast-api-backend && uvicorn main:app --host 0.0.0.0 --port 8000 &",
    "cd random_name_frontend && npm start"
  ]
