[phases.build]
cmds = [
  "cd fast-api-backend && pip install -r requirements.txt",
  "cd random_name_frontend && npm install",
  "cd random_name_frontend && npm run build"
]

[start]
cmd = "cd fast-api-backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} & cd random_name_frontend && npm start"
